language: java
before_script:
  - export TZ=America/Sao_Paulo

jdk:
  - oraclejdk8

notifications:
    email:
        recipients:
            - falci.exe@gmail.com
        on_success: change
        on_failure: always
        
sudo: false
